##### Fahad vadakkumpadath
5/10/2020

### Session: 1

##### Importing pyTorch

In [119]:
import numpy as np 
import torch
torch.__version__

'1.4.0'

##### Helper function to display type,shape and values

In [81]:
def describe(x):
    print("Type : {}".format(x.type()))
    print("Size/shape : {}".format(x.shape))
    print("Values :\n {}".format(x))

### Creating a tensor in PyTorch with torch.Tensor
##### The dimensions of the tensors can be given in two ways as shown above. Please note that the data types of the tensors are important as we will see later

In [107]:
x = torch.empty([5, 3])
describe(x)

Type : torch.FloatTensor
Size/shape : torch.Size([5, 3])
Values :
 tensor([[1.0194e-38, 9.6429e-39, 9.2755e-39],
        [9.1837e-39, 9.3674e-39, 1.0745e-38],
        [1.0653e-38, 9.5510e-39, 1.0561e-38],
        [1.0194e-38, 1.1112e-38, 1.0561e-38],
        [9.9184e-39, 1.0653e-38, 4.1327e-39]])


In [108]:
y = torch.empty(5, 3)
describe(y)

Type : torch.FloatTensor
Size/shape : torch.Size([5, 3])
Values :
 tensor([[9.2755e-39, 9.1837e-39, 9.3674e-39],
        [1.0745e-38, 1.0653e-38, 9.5510e-39],
        [1.0561e-38, 1.0194e-38, 1.1112e-38],
        [1.0561e-38, 9.9184e-39, 1.0653e-38],
        [4.1327e-39, 1.0194e-38, 1.0469e-38]])


In [115]:
a = torch.rand(5, 4) # uniform random
# describe(torch.randn(2, 3)) # random normal
describe(a)

Type : torch.FloatTensor
Size/shape : torch.Size([5, 4])
Values :
 tensor([[0.3417, 0.8136, 0.1445, 0.4473],
        [0.4718, 0.5163, 0.9054, 0.7821],
        [0.7305, 0.2383, 0.4729, 0.9269],
        [0.9817, 0.4320, 0.3108, 0.0596],
        [0.0778, 0.9928, 0.7472, 0.5134]])


##### Creating a filled tensor

In [96]:
z = torch.zeros(5, 3, dtype=torch.long)
describe(z)

Type : torch.LongTensor
Size/shape : torch.Size([5, 3])
Values :
 tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
None


In [116]:
x = torch.ones(2, 3)
describe(x)
x.fill_(5)
describe(x)

Type : torch.FloatTensor
Size/shape : torch.Size([2, 3])
Values :
 tensor([[1., 1., 1.],
        [1., 1., 1.]])
Type : torch.FloatTensor
Size/shape : torch.Size([2, 3])
Values :
 tensor([[5., 5., 5.],
        [5., 5., 5.]])


##### Any PyTorch method with an underscore(_) refers to an inplace operation; that is, it modifies the content in place without creating a new object.
##### We can specify the data type in the above way. For a complete list of all the available datatypes, refer to this link: https://pytorch.org/docs/stable/tensors.html

##### Creating and initializing a tensor from lists

In [117]:
x = torch.Tensor([[1, 2, 3],[4, 5, 6]])
describe(x)

Type : torch.FloatTensor
Size/shape : torch.Size([2, 3])
Values :
 tensor([[1., 2., 3.],
        [4., 5., 6.]])


##### Creating and initializing a tensor from NumPy

In [118]:
npy = np.random.rand(2, 3)
describe(torch.from_numpy(npy))

Type : torch.DoubleTensor
Size/shape : torch.Size([2, 3])
Values :
 tensor([[0.0511, 0.2645, 0.4781],
        [0.7214, 0.9175, 0.3604]], dtype=torch.float64)


##### Tensor properties

In [120]:
x = torch.FloatTensor([[1, 2, 3],[4, 5, 6]])
describe(x)

Type : torch.FloatTensor
Size/shape : torch.Size([2, 3])
Values :
 tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [121]:
x = x.long()
describe(x)

Type : torch.LongTensor
Size/shape : torch.Size([2, 3])
Values :
 tensor([[1, 2, 3],
        [4, 5, 6]])


In [122]:
x = torch.tensor([[1, 2, 3],[4, 5, 6]], dtype=torch.int64)
describe(x)

Type : torch.LongTensor
Size/shape : torch.Size([2, 3])
Values :
 tensor([[1, 2, 3],
        [4, 5, 6]])


In [123]:
x = x.float()
describe(x)

Type : torch.FloatTensor
Size/shape : torch.Size([2, 3])
Values :
 tensor([[1., 2., 3.],
        [4., 5., 6.]])


##### Tensor Operations

In [ ]:
x = torch.randn(2, 3)
describe(x)

In [ ]:
describe(torch.add(x, x))

In [ ]:
describe(x + x)

##### Dimensionbased tensor operations

In [ ]:
x = torch.arange(6)
describe(x)

In [124]:
x = x.view(2, 3)
describe(x)

Type : torch.FloatTensor
Size/shape : torch.Size([2, 3])
Values :
 tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [125]:
describe(torch.sum(x, dim=0))

Type : torch.FloatTensor
Size/shape : torch.Size([3])
Values :
 tensor([5., 7., 9.])


In [126]:
describe(torch.sum(x, dim=1))

Type : torch.FloatTensor
Size/shape : torch.Size([2])
Values :
 tensor([ 6., 15.])


In [127]:
describe(torch.transpose(x, 0, 1))

Type : torch.FloatTensor
Size/shape : torch.Size([3, 2])
Values :
 tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


##### Slicing and indexing a tensor

In [128]:
x = torch.arange(6).view(2, 3)
describe(x)

Type : torch.LongTensor
Size/shape : torch.Size([2, 3])
Values :
 tensor([[0, 1, 2],
        [3, 4, 5]])


In [ ]:
describe(x[:1, :2])

In [ ]:
describe(x[0, 1])

##### Complex indexing: noncontiguous indexing of a tensor

In [ ]:
indices = torch.LongTensor([0, 2])
describe(torch.index_select(x, dim=1, index=indices))

In [ ]:
indices = torch.LongTensor([0, 0])
describe(torch.index_select(x, dim=0, index=indices))

In [ ]:
row_indices = torch.arange(2).long()
col_indices = torch.LongTensor([0, 1])
describe(x[row_indices, col_indices])

##### Concatenating tensors

In [ ]:
import torch
x = torch.arange(6).view(2,3)
describe(x)

In [ ]:
describe(torch.cat([x, x], dim=0))

In [ ]:
describe(torch.cat([x, x], dim=1))

In [ ]:
describe(torch.stack([x, x]))

##### Linear algebra on tensors: multiplication

In [129]:
x1 = torch.arange(6).view(2, 3)
describe(x1)

Type : torch.LongTensor
Size/shape : torch.Size([2, 3])
Values :
 tensor([[0, 1, 2],
        [3, 4, 5]])


In [ ]:
x2 = torch.ones(3, 2)
x2[:, 1] += 1
describe(x2)

In [ ]:
describe(torch.mm(x1, x2))

###### Creating tensors for gradient bookkeeping

In [ ]:
x = torch.ones(2, 2, requires_grad=True)
describe(x)
print(x.grad is None)

In [ ]:
y = (x + 2) * (x + 5) + 3
describe(y)
print(x.grad is None)

In [ ]:
z = y.mean()
describe(z)
z.backward()
print(x.grad is None)

##### When you create a tensor with requires_grad=True, you are requiring PyTorch to manage bookkeeping information that computes gradients
##### In PyTorch, you can access the gradients for the nodes in the computational graph by using the .grad member variable. Optimizers use the .grad variable to update the values of the parameters.

##### CUDA Tensors

In [130]:
o use a GPU, you need to first
allocate the tensor on the GPU’s memory

Access to the GPUs is via a specialized API called CUDA.

o use a GPU, you need to first
allocate the tensor on the GPU’s memory


SyntaxError: invalid syntax (<ipython-input-130-90c3dd24661d>, line 1)

##### Creating CUDA tensors

In [ ]:
print (torch.cuda.is_available())

In [ ]:
# preferred method: device agnostic tensor instantiation
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print (device)

In [ ]:
x = torch.rand(3, 3).to(device)
describe(x)

##### Mixing CUDA tensors with CPUbound tensors

In [ ]:
y = torch.rand(3, 3)
x + y

In [ ]:
cpu_device = torch.device("cpu")
y = y.to(cpu_device)
x = x.to(cpu_device)
x + y

### End of session:1